on: 
  push:
    branches: 
      - master
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build appbundle
      - uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNINKEYBASE64 }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTOREPASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEYPASSWORD }}
      - uses: actions/upload-artifact@v2
        with:
          name: Release AAB
          path: ${{ steps.sign-app.outputs.signedReleaseFile }}
