on:
  push:
    tags:
      - 'v*'
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: echo $KEY_JKS | base64 -d > android/app/androidsign.jks
        env:
          KEY_JKS: ${{ secrets.ANDROID_SIGNINKEYBASE64 }}
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build appbundle
        env:
          KEY_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTOREPASSWORD }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEYPASSWORD }}
          ALIAS: ${{ secrets.ANDROID_ALIAS }}
          KEY_PATH: androidsign.jks
      - uses: actions/upload-artifact@v2
        with:
          name: Release AAB
          path: build/app/outputs/bundle/release/*.aab
